name: kims_liver_transplant
description: "KIMS Liver Transplant - Patient Mobile Application for post-transplant care management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.0
  intl: ^0.19.0
  fl_chart: ^0.65.0
  image_picker: ^1.0.4
  permission_handler: 12.0.1
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  table_calendar: ^3.0.9
  dotted_border: ^2.1.0
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/logo/KIMS.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo/KIMS.png

